version: '3'

name: niyo-tms

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    restart: unless-stopped
    links:
      - db:db
    volumes:
      - web_data:/opt/project
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine
    ports:
      - 5432:5432
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  web_data:
  postgres_data:
